[versions]
agp = "8.7.2"
kotlin = "2.0.21"
coreKtx = "1.10.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
kotlinxCoroutinesTest = "1.9.0"
material = "1.12.0"
constraintlayout = "2.2.0"
navigationFragmentKtx = "2.8.4"
navigationUiKtx = "2.8.4"
dagger = "2.53.1"
paging = "3.3.5"
room = "2.6.1"
retrofit = "2.11.0"
moshi = "1.15.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
#logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
paging3-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging"}
room-runtime = { group = "androidx.room", name = "room-paging", version.ref = "room"}
retrofit_runtime = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
retrofit_moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit"}
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger"}

ksp = { id = "com.google.devtools.ksp", version = "2.0.21-1.0.28" }

